---
- name: Create VM image from base
  copy:
    dest: "{{ item.pool_home }}/image_{{ item.name }}.img"
    src: "{{ image_pool_dir }}/{{ base_image_name }}"
  register: copy_results
- name: Create user data from template
  template:
    src: user-data.yaml.j2
    dest: "{{ item.pool_home }}/{{ item.name }}-user-data.yaml"
    mode: 0644
- name: Create network config from template
  template:
    src: network_config_static.cfg.j2
    dest: "{{ item.pool_home }}/{{ item.name }}-network_config_static.cfg"
    mode: 0644
- name: Resize the image
  command: |
    qemu-img resize "{{ item.pool_home }}/image_{{ item.name }}.img" "{{ item.disk_size }}"
- name: Create cloud init disk
  command: |
    cloud-localds -v --network-config="{{ item.pool_home }}/{{ item.name }}-network_config_static.cfg" "{{ item.pool_home }}/image_{{ item.name }}_seed.img" "{{ item.pool_home }}/{{ item.name }}-user-data.yaml"
- name: Create the VM
  command: |
    virt-install \
    --name {{ item.name }} \
    --memory {{ item.ram_mb }} \
    --vcpus {{ item.vcpus }} \
    --disk "{{ item.pool_home }}/image_{{ item.name }}.img",device=disk,bus=virtio \
    --disk "{{ item.pool_home }}/image_{{ item.name }}_seed.img",readonly=on \
    --import \
    --os-variant debian11 \
    --graphics none \
    --noautoconsole \
    --network bridge="virbr-{{ clusterName }}"
