---
- include_vars: kvms.json
- name: Generating the SSH-key for Ansible
  include_tasks: generate_ssh_keys.yml
- name: Ensure requirements in place
  package:
    name:
      - libguestfs-tools
      - python3-libvirt
      - libvirt-devel
      - cloud-utils # debian-family cloud-image-utils
    state: present
  become: true
- name: Create network for cluster
  include_tasks: create_network.yml
- name: Get VMs list
  community.libvirt.virt:
    command: list_vms
  register: existing_vms
  changed_when: false
- name: Check is base image present
  ansible.builtin.stat:
    path: "{{ image_pool_dir }}/{{ base_image_name }}"
  register: stat_result
- name: Download base image
  become: yes
  get_url:
    url: "{{ base_image_url }}"
    dest: "{{ image_pool_dir }}/{{ base_image_name }}"
    checksum: "{{ base_image_checksum }}"
  register: base_image
  when: not stat_result.stat.exists
- name: create the master vms
  include_tasks: create_kvm.yml
  vars:
    vm_name: "{{ item.name }}{{ clusterName }}"
  loop: "{{ masters }}"
- name: create the worker vms
  include_tasks: create_kvm.yml
  vars:
    vm_name: "{{ item.name }}{{ inventory_hostname }}"
  loop: "{{ workers }}"
- name: wait for VMs to finish installing
  wait_for:
    timeout: 30
